Avoid posting review if comments are empty
linuxdeepin/action-cppcheck pull request #11
Opened 2022-04-08 14:24 UTC by ikerexxe

Test results can be reviewed in https://github.com/ikerexxe/test-1/pull/2

2022-04-08 14:44 UTC, myml requested changes

2022-04-08 14:44 UTC, myml commented on cmd/action-cppcheck/main.go
> +	if len(comments) > 0 {
Need comment_result is false
like
```
if comments == 0 && !comment_result{
return
}
```

2022-04-08 15:10 UTC, ikerexxe commented on cmd/action-cppcheck/main.go
> +	if len(comments) > 0 {
There's no need for that. It's already implied that if `comments` is empty, then `comment_result` is false.

2022-04-08 15:43 UTC, myml commented on cmd/action-cppcheck/main.go
> +	if len(comments) > 0 {
Comment result is optional. If comments is not null and comment result is true, should post good words.

2022-04-11 08:01 UTC, ikerexxe commented on cmd/action-cppcheck/main.go
> +	if len(comments) > 0 {
You are right. I've updated the code accordingly.

2022-04-11 08:02 UTC, ikerexxe commented
I've updated the code and rerun the check in https://github.com/ikerexxe/test-1/pull/2

2022-04-11 08:34 UTC, myml requested changes

2022-04-11 08:34 UTC, myml commented on cmd/action-cppcheck/main.go
> +	if len(comments) > 0 {
This 'if' needs to be removed to send "good comment"

2022-04-11 08:43 UTC, ikerexxe commented on cmd/action-cppcheck/main.go
> +	if len(comments) > 0 {
Done

2022-04-11 10:13 UTC, myml commented
thank for you contribution!

2022-04-11 10:13 UTC, merged